### ISSUE TITLE
Exception when parsing stacktrace in exception

### ISSUE THREAD

**Issue by leo-labs** [Miaplaza/logstash-filter-csharp#1]
```
[2017-10-23T15:39:08,099][FATAL][logstash.runner] An unexpected error occurred! {
:error=>#<NoMethodError: undefined method `split' for nil:NilClass>, 
:backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-csharp-0.1.0/lib/logstash/filters/csharp.rb:21:in `parse_stacktrace'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-csharp-0.1.0/lib/logstash/filters/csharp.rb:61:in `parse_exception'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-csharp-0.1.0/lib/logstash/filters/csharp.rb:59:in `parse_exception'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-csharp-0.1.0/lib/logstash/filters/csharp.rb:87:in `filter'", 
"/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", 
"/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:164:in `multi_filter'", 
"org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", 
"/usr/share/logstash/logstash-core/lib/logstash/filter_delegator.rb:43:in `multi_filter'", "(eval):2985:in `initialize'", 
"org/jruby/RubyArray.java:1613:in `each'", "(eval):2982:in `initialize'", 
"org/jruby/RubyProc.java:281:in `call'", "(eval):3011:in `initialize'", 
"org/jruby/RubyArray.java:1613:in `each'", "(eval):2996:in `initialize'", 
"org/jruby/RubyProc.java:281:in `call'", "(eval):673:in `filter_func'", 
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:383:in `filter_batch'",
"org/jruby/RubyProc.java:281:in `call'", 
"/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:238:in `each'",
"org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:237:in `each'", 
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:382:in `filter_batch'", 
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:363:in `worker_loop'", 
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:330:in `start_workers'"]}
```
This happens inside `InnerExceptions`s so the StackTraceString property might be null because it was eaten by some Exception Handler before, or another reason.

in https://github.com/Miaplaza/logstash-filter-csharp/commit/5103d4e4b36aa0eab3f115a0ea269d4cadd6cd1f#diff-5579bd29f463ffbc35548bc6441eda7bR64

**Comment by leo-labs** [comment]
This fixes the issue we had.
